name: Build & Distribute Android App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Android and Distribute to Firebase
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.10.0

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Decode Firebase Service Account
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/firebase-service-account.json

      - name: Set Environment Variable for Firebase
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json" >> $GITHUB_ENV

      - name: Build Android APK with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile development --non-interactive | tee build.log

      - name: Extract last APK URL from build output
        id: extract_url
        run: |
          APK_URL=$(grep "https://expo.dev/artifacts/eas/" build.log | tail -1)
          echo "APK_URL=$APK_URL" >> $GITHUB_OUTPUT

      - name: Download APK
        run: |
          echo "Downloading APK from ${{ steps.extract_url.outputs.APK_URL }}"
          curl -L -o app.apk "${{ steps.extract_url.outputs.APK_URL }}"

      - name: Decode Firebase Service Account
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/firebase-service-account.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS env var
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json" >> $GITHUB_ENV

      - name: Distribute APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ./app.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
